# fly.toml app configuration file generated for pokeman on 2023-08-16T12:13:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokeman"
primary_region = "arn"

[build]

[deploy]
  release_command = "npm run build"
  strategy = "bluegreen"

[processes]
  app = "node app.js"

[[services]]
  protocol = ""
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/version"
    protocol = "http"
    tls_skip_verify = false
