# fly.toml app configuration file generated for pokeman on 2023-08-16T09:55:13+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokeman"
primary_region = "arn"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.0"
